version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.4.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-react-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: yarn push:check
      - run:
          name: Run tests with JUnit as reporter
          command: yarn test:junit
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - save_cache:
          key: v1-react-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
